routes/web.php
        Route::resource('data-master/kurikulum', '\App\Http\Controllers\DataMaster\KurikulumController');
        Route::resource('data-master/tahun_akademik', '\App\Http\Controllers\DataMaster\TahunAkademikController');
        Route::resource('data-master/ruang_kelas', '\App\Http\Controllers\DataMaster\RuangKelasController');
        Route::resource('data-master/agama', '\App\Http\Controllers\DataMaster\AgamaController');
        Route::resource('data-master/jabatan', '\App\Http\Controllers\DataMaster\JabatanController');
        Route::resource('data-master/bagian', '\App\Http\Controllers\DataMaster\BagianController');
        Route::resource('data-master/pendapatan', '\App\Http\Controllers\DataMaster\PendapatanController');
        Route::resource('data-master/status_karyawan', '\App\Http\Controllers\DataMaster\StatusKaryawanController');
        Route::resource('data-master/kendaraan', '\App\Http\Controllers\DataMaster\KendaraanController');
        Route::resource('data-master/rombongan_belajar', '\App\Http\Controllers\DataMaster\RombonganBelajarController');
        Route::resource('data-master/data_guru', '\App\Http\Controllers\DataMaster\DataGuruController');
        Route::resource('data-master/wali_kelas', '\App\Http\Controllers\DataMaster\WaliKelasController');
        Route::resource('data-master/kelas', '\App\Http\Controllers\DataMaster\KelasController');
        Route::resource('data-master/jenjang', '\App\Http\Controllers\DataMaster\JenjangController');
        //akademik
        Route::resource('akademik/mata_pelajaran', '\App\Http\Controllers\Akademik\MataPelajaranController');
        Route::resource('akademik/raport', '\App\Http\Controllers\Akademik\RaportController');
        Route::resource('manajemen/akademik/jadwal-mata-pelajaran', '\App\Http\Controllers\Akademik\JadwalMataPelajaranController');
        Route::resource('manajemen/siswa', '\App\Http\Controllers\ManajemenSiswa\SiswaController');
        Route::get('akademik/data-orang-tua', [
            'uses'      => '\App\Http\Controllers\Akademik\DataOrangTuaController@index',
            'as'        => 'data-orang-tua.index'
        ]);
        Route::resource('akademik/ekstrakurikuler', '\App\Http\Controllers\Akademik\EkstrakurikulerController');
        Route::resource('akademik/bimbingan-belajar', '\App\Http\Controllers\Akademik\BimbinganBelajarController');
        Route::resource('akademik/data-alumni', '\App\Http\Controllers\Akademik\DataAlumniController');
        Route::resource('akademik/mata-pelajar-perkelas', '\App\Http\Controllers\Akademik\MataPelajarPerkelasController');
        Route::resource('akademik/mata-pelajaran-guru', '\App\Http\Controllers\Akademik\MataPelajaranGuruController');
        Route::resource('akademik/grid-nilai', '\App\Http\Controllers\Akademik\GridNilaiController');
        Route::resource('akademik/siswa-perkelas', '\App\Http\Controllers\Akademik\SiswaPerkelasController');
        Route::resource('akademik/nilai-per-mata-pelajaran', '\App\Http\Controllers\Akademik\NilaiPermapelController');
        Route::resource('akademik/nilai-per-kelas', '\App\Http\Controllers\Akademik\NilaiPerkelasController');
        Route::resource('akademik/ekstra-siswa', '\App\Http\Controllers\Akademik\EktraSiswaController');
        //psb
        Route::resource('siswa/daftar-siswa', '\App\Http\Controllers\Psb\PsbDaftarSiswaController');
        Route::resource('psb/test-interview', '\App\Http\Controllers\Psb\TestInterviewController');
        Route::resource('psb/hasil-ujian', '\App\Http\Controllers\Psb\PsbHasilUjianController');
        Route::get('psb/siswa-diterima', [
            'uses'  => '\App\Http\Controllers\Psb\PsbSiswaDiterimaController@index',
            'as'    => 'siswa-diterima.index'
        ]);

        //manajemen keuangan siswa
        Route::resource('manajemen/keuangan-siswa/jenis-pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\JenisPembyaranController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-spp', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSppController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-semester', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSemesterController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-buku', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranBukuController');
        Route::resource('manajemen/keuangan-siswa/pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranController');

        //manajement guru
        Route::resource('manajemen/kehadiran-guru', '\App\Http\Controllers\ManajemenGuru\KehadiranGuruController');
        //manajemen keuangan siswa
        Route::resource('manajemen/keuangan-siswa/jenis-pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\JenisPembyaranController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-spp', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSppController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-semester', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSemesterController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-buku', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranBukuController');
        Route::resource('manajemen/keuangan-siswa/pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranController');
        //staff
        Route::resource('manajemen/staff', '\App\Http\Controllers\Staff\StaffController');
        //perpustakaan
        Route::resource('perpustakaan/data-buku', '\App\Http\Controllers\Perpustakaan\DataBukuController');
        Route::resource('perpustakaan/peminjaman-buku', '\App\Http\Controllers\Perpustakaan\PeminjamanBukuController');
        Route::resource('perpustakaan/pengembalian-buku', '\App\Http\Controllers\Perpustakaan\PengembalianBukuController');
        Route::resource('perpustakaan/petugas', '\App\Http\Controllers\Perpustakaan\PetugasPerpustakaanController');
        //inventories
        Route::resource('inventori/kategori-inventori', '\App\Http\Controllers\Inventori\KategoriInventoriController');
        Route::resource('inventori/tipe-inventori', '\App\Http\Controllers\Inventori\TipeInventoryController');
        Route::resource('inventori/gedung', '\App\Http\Controllers\Inventori\GedungController');
        Route::resource('inventori/tipe-donasi', '\App\Http\Controllers\Inventori\TipeDonasiController');
        Route::resource('inventori/asset', '\App\Http\Controllers\Inventori\AssetController');
        Route::resource('inventori/donasi', '\App\Http\Controllers\Inventori\DonasiController');
        Route::resource('inventori/barang', '\App\Http\Controllers\Inventori\BarangController');
        Route::resource('inventori/barang-masuk', '\App\Http\Controllers\Inventori\BarangMasukController');
        Route::resource('inventori/barang-keluar', '\App\Http\Controllers\Inventori\BarangKeluarController');
        Route::resource('inventori/spk-asset', '\App\Http\Controllers\Inventori\SPKAssetController');
        //accounting
        Route::resource('accounting/tipe-pajak', '\App\Http\Controllers\Accounting\TipePajakController');
        //pengeluaran
        Route::resource('accounting/pengeluaran/uang-masuk', '\App\Http\Controllers\Accounting\Pengeluaran\PengeluaranUangMasukController');
        Route::resource('accounting/pengeluaran/permintaan-dana', '\App\Http\Controllers\Accounting\Pengeluaran\PermintaanDanaController');
        Route::resource('accounting/pengeluaran/cek-list', '\App\Http\Controllers\Accounting\Pengeluaran\PengeluaranCekListController');
        Route::resource('accounting/pengeluaran/reibusment', '\App\Http\Controllers\Accounting\Pengeluaran\ReibustmentController');
        Route::resource('accounting/pengeluaran/jurnal-edc', '\App\Http\Controllers\Accounting\Pengeluaran\JurnalEdcController');
        Route::resource('accounting/pengeluaran/jurnal-uang-keluar', '\App\Http\Controllers\Accounting\Pengeluaran\JurnalUangKeluarController');
        Route::resource('accounting/pengeluaran/kas-mutasi', '\App\Http\Controllers\Accounting\Pengeluaran\JurnalKasMutasiController');
        Route::resource('accounting/pengeluaran/dana-pending', '\App\Http\Controllers\Accounting\Pengeluaran\DanaPendingController');
        //pemasukan
        Route::resource('accounting/pemasukan/rekening-siswa', '\App\Http\Controllers\Accounting\Pemasukan\RekeningSiswaController');
        Route::resource('accounting/pemasukan/jurnal-pbn', '\App\Http\Controllers\Accounting\Pemasukan\JurnalPbnController');
        Route::resource('accounting/pemasukan/jurnal-spp', '\App\Http\Controllers\Accounting\Pemasukan\JurnalSppController');
        Route::resource('accounting/pemasukan/jurnal-program-bulanan', '\App\Http\Controllers\Accounting\Pemasukan\JurnalProController');
        Route::resource('accounting/pemasukan/cut-off-siswa', '\App\Http\Controllers\Accounting\Pemasukan\CutOffSiswaController');
        Route::resource('accounting/pemasukan/hutang', '\App\Http\Controllers\Accounting\Pemasukan\HutangController');
        Route::resource('accounting/coa', '\App\Http\Controllers\Accounting\CoaController');
        
        //elearning
        Route::resource('elearning/tugas', '\App\Http\Controllers\Elearning\EtugasController');
        Route::resource('elearning/e-kelas', '\App\Http\Controllers\Elearning\EkelasController');
        Route::resource('elearning/materi', '\App\Http\Controllers\Elearning\EmateriController');
        Route::resource('elearning/quiz', '\App\Http\Controllers\Elearning\EquizController');
        Route::resource('elearning/pengumuman', '\App\Http\Controllers\Elearning\EpengumumanController');
        
        //pengumuman events
        Route::get('pengumuman/event/create', [
            'uses'      => '\App\Http\Controllers\Pengumuman\PengumumanEventsController@create',
            'as'        => 'pengumuman.event.create'
        ]);

resources/views/data_siswa/daftar_siswa/create.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Pendaftaran Siswa Baru</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				 <!-- form start -->
                 {{ Form::open(array('route' => 'daftar-siswa.store', 'files' => true, 'enctype' => 'multipart/form-data')) }}
	              <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">No Pendaftaran</label>
                            {!! Form::text('no_pendaftaran', old('no_pendaftaran'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Nama Lengkap</label>
                            {!! Form::text('nama_lengkap', old('nama_lengkap'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                            <label for="nama">Jenis Kelamin</label>
                            {!! Form::text('jenis_kelamin', old('jenis_kelamin'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                            <label for="nama">Tempat Lahir</label>
                            {!! Form::text('tempat_lahir', old('tempat_lahir'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                            <label for="nama">Tanggal Lahir</label>
                            {!! Form::date('tanggal_lahir', old('tanggal_lahir'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                            <label for="nama">Alamat</label>
                            {!! Form::text('alamat', old('alamat'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Nomor Telp</label>
                            {!! Form::text('telp', old('telp'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Jenjang</label>
                             @if(!$jenjangs->isEmpty())
                                <select name="jenjang_id" class="form-control">
                                    @foreach($jenjangs as $jenjang)
                                        <option value="{{ $jenjang->id }}">
                                            {{ $jenjang->nama_jenjang }}
                                        </option>
                                    @endforeach
                                </select>
                             @else
                                <div class="dataempty">
                                    data empty
                                </div>
                             @endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Email</label>
                            {!! Form::text('email', old('email'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Nomor WA</label>
                            {!! Form::text('no_wa', old('no_wa'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Jurusan</label>
                             @if(!$jurusans->isEmpty())
                                <select name="jurusan_id" class="form-control">
                                    @foreach($jurusans as $jurusan)
                                        <option value="{{ $jurusan->id }}">
                                            {{ $jurusan->nama_jurusan }}
                                        </option>
                                    @endforeach
                                </select>
                             @else
                                <div class="dataempty">
                                    data empty
                                </div>
                             @endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Nama Orang Tua</label>
                            {!! Form::text('nama_orang_tua', old('nama_orang_tua'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Pekerjaan Orang Tua</label>
                            {!! Form::text('pekerjaan_orang_tua', old('pekerjaan_orang_tua'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Nomor Telp Orang Tua</label>
                            {!! Form::text('no_telp_ortu', old('no_telp_ortu'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Penghasilan Orang Tua</label>
                            {!! Form::text('penghasilan_ortu', old('penghasilan_ortu'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="nama">Photo</label>
                            {!! Form::file('photo', old('photo'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-md-6" style="margin-top: 15px;">
	                 	<div class="box-footer">
			                <button type="submit" class="btn btn-primary">Simpan</button>
			            </div>
	                 </div>
	            {!! Form::close() !!}
					
				</div>
				<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
@endsection

resources/views/data_siswa/daftar_siswa/index.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Daftar Siswa</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
				    <li class="breadcrumb-item active" aria-current="page">Daftar Siswa</li>
				  </ol>
				</nav>
				<div class="box-header with-border">
					<a href="{{ route('daftar-siswa.create') }}" class="btn btn-sm btn-primary">
						<i class="fa fa-plus" aria-hidden="true"></i>
					</a>
				</div>
				<table class="table table-bordered">
					@if(!$daftarSiswas->isEmpty())
						<tr>
							<th style="width: 10px">#</th>
							<th>Nomor Daftar</th>
							<th>Nama Lengkap</th>
							<th>Jenis Kelamin</th>
							<th>Jenjang</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
						@foreach($daftarSiswas as $daftarSiswa)
							<tr>
								<td>{{ $loop->index +1 }}</td>
								<td>{{ $daftarSiswa->no_pendaftaran }}</td>
								<td>{{ $daftarSiswa->nama_lengkap }}</td>
								<td>{{ $daftarSiswa->jenis_kelamin }}</td>
								<td>{{ $daftarSiswa->jenjang->nama_jenjang }}</td>
								<td>{{ $daftarSiswa->status }}</td>
								<td>
									<a href="{{ route('daftar-siswa.show', ['daftar-siswa' => $daftarSiswa->id]) }}" class="btn btn-sm btn-warning">
										<i class="fa fa-eye" aria-hidden="true"></i>
									</a>
									<a href="{{ route('daftar-siswa.edit', ['daftar-siswa' => $daftarSiswa->id]) }}" class="btn btn-sm btn-success">
										<i class="fa fa-pencil" aria-hidden="true"></i>
									</a>
									{!! Form::open(['route' => ['daftar-siswa.destroy', $daftarSiswa->id], 'method' => 'DELETE', 'style' => 'display:inline;']) !!}
										<button class="btn btn-sm btn-danger btn-delete" type="submit">
											<i class="fa fa-trash" aria-hidden="true"></i>
										</button>
                                    {!! Form::close() !!}
								</td>
							</tr>
						@endforeach
					@else
                        <div class="alert alert-danger">
                            Data empty
                        </div>
                    @endif
				</table>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
				{{ $daftarSiswas->links() }}
			</div> 
		</div>
		<!-- /.box -->
	</div>
@endsection

resources/views/data_siswa/daftar_siswa/show.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Detail Daftar Siswa</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
				    <li class="breadcrumb-item active" aria-current="page">Detail Daftar Siswa</li>
				  </ol>
				</nav>
				<div class="box-header with-border">
					<a href="{{ route('daftar-siswa.index') }}" class="btn btn-sm btn-primary">
						Siswa Baru
					</a>
				</div>
				<table class="table table-bordered">
						<tr>
                            <td style="font-weight:bold;">Nomor Pendaftaran</td>
                            <td>{{ $daftarSiswa->no_pendaftaran }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Nama Lengkap</td>
                            <td>{{ $daftarSiswa->nama_lengkap }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Jenis Kelamin</td>
                            <td>{{ $daftarSiswa->jenis_kelamin }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Tempat Lahir</td>
                            <td>{{ $daftarSiswa->tempat_lahir }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Tanggal Lahir</td>
                            <td>{{ $daftarSiswa->tanggal_lahir }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Alamat</td>
                            <td>{{ $daftarSiswa->alamat }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Nomor Telp</td>
                            <td>{{ $daftarSiswa->telp }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Jenjang</td>
                            <td>{{ $daftarSiswa->jenjang->nama_jenjang }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Email</td>
                            <td>{{ $daftarSiswa->email }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Nomor WA</td>
                            <td>{{ $daftarSiswa->no_wa }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Jurusan</td>
                            <td>{{ $daftarSiswa->jurusan->nama_jurusan }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Nama Orang Tua</td>
                            <td>{{ $daftarSiswa->nama_orang_tua }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Pekerjaan Orang Tua</td>
                            <td>{{ $daftarSiswa->pekerjaan_orang_tua }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Nomor Telp Orang Tua</td>
                            <td>{{ $daftarSiswa->no_telp_ortu }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Penghasilan Orang Tua</td>
                            <td>{{ $daftarSiswa->penghasilan_ortu }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold;">Photo</td>
                            <td>
                            <img src="{{ asset('psb/'. $daftarSiswa->photo) }}" alt="news image" class="img-fluid" style="width:100px; heigt: 100px; border-radius: 5px;">
                            </td>
                        </tr>
				</table>
			</div>
			<!-- /.box-body -->
			<!-- <div class="box-footer clearfix">
				<ul class="pagination pagination-sm no-margin pull-right">
					<li><a href="#">&laquo;</a></li>
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">&raquo;</a></li>
				</ul>
			</div> -->
		</div>
		<!-- /.box -->
	</div>
@endsection