routes/web.php
        Route::resource('data-master/ruang_kelas', '\App\Http\Controllers\DataMaster\RuangKelasController');
        Route::resource('data-master/agama', '\App\Http\Controllers\DataMaster\AgamaController');
        Route::resource('data-master/jabatan', '\App\Http\Controllers\DataMaster\JabatanController');
        Route::resource('data-master/bagian', '\App\Http\Controllers\DataMaster\BagianController');
        Route::resource('data-master/pendapatan', '\App\Http\Controllers\DataMaster\PendapatanController');
        Route::resource('data-master/status_karyawan', '\App\Http\Controllers\DataMaster\StatusKaryawanController');
        Route::resource('data-master/kendaraan', '\App\Http\Controllers\DataMaster\KendaraanController');
        Route::resource('data-master/rombongan_belajar', '\App\Http\Controllers\DataMaster\RombonganBelajarController');
        Route::resource('data-master/data_guru', '\App\Http\Controllers\DataMaster\DataGuruController');
        Route::resource('data-master/wali_kelas', '\App\Http\Controllers\DataMaster\WaliKelasController');
        Route::resource('data-master/kelas', '\App\Http\Controllers\DataMaster\KelasController');
        Route::resource('data-master/jenjang', '\App\Http\Controllers\DataMaster\JenjangController');
        //akademik
        Route::resource('akademik/mata_pelajaran', '\App\Http\Controllers\Akademik\MataPelajaranController');
        Route::resource('akademik/raport', '\App\Http\Controllers\Akademik\RaportController');
        Route::resource('manajemen/akademik/jadwal-mata-pelajaran', '\App\Http\Controllers\Akademik\JadwalMataPelajaranController');
        Route::resource('manajemen/siswa', '\App\Http\Controllers\ManajemenSiswa\SiswaController');
        Route::get('akademik/data-orang-tua', [
            'uses'      => '\App\Http\Controllers\Akademik\DataOrangTuaController@index',
            'as'        => 'data-orang-tua.index'
        ]);
        Route::resource('akademik/ekstrakurikuler', '\App\Http\Controllers\Akademik\EkstrakurikulerController');
        Route::resource('akademik/bimbingan-belajar', '\App\Http\Controllers\Akademik\BimbinganBelajarController');
        Route::resource('akademik/data-alumni', '\App\Http\Controllers\Akademik\DataAlumniController');
        Route::resource('akademik/mata-pelajar-perkelas', '\App\Http\Controllers\Akademik\MataPelajarPerkelasController');
        Route::resource('akademik/mata-pelajaran-guru', '\App\Http\Controllers\Akademik\MataPelajaranGuruController');
        Route::resource('akademik/grid-nilai', '\App\Http\Controllers\Akademik\GridNilaiController');
        Route::resource('akademik/siswa-perkelas', '\App\Http\Controllers\Akademik\SiswaPerkelasController');
        Route::resource('akademik/nilai-per-mata-pelajaran', '\App\Http\Controllers\Akademik\NilaiPermapelController');
        Route::resource('akademik/nilai-per-kelas', '\App\Http\Controllers\Akademik\NilaiPerkelasController');
        Route::resource('akademik/ekstra-siswa', '\App\Http\Controllers\Akademik\EktraSiswaController');
        //psb
        Route::resource('siswa/daftar-siswa', '\App\Http\Controllers\Psb\PsbDaftarSiswaController');
        Route::resource('psb/test-interview', '\App\Http\Controllers\Psb\TestInterviewController');
        Route::resource('psb/hasil-ujian', '\App\Http\Controllers\Psb\PsbHasilUjianController');
        Route::get('psb/siswa-diterima', [
            'uses'  => '\App\Http\Controllers\Psb\PsbSiswaDiterimaController@index',
            'as'    => 'siswa-diterima.index'
        ]);

        //manajemen keuangan siswa
        Route::resource('manajemen/keuangan-siswa/jenis-pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\JenisPembyaranController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-spp', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSppController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-semester', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSemesterController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-buku', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranBukuController');
        Route::resource('manajemen/keuangan-siswa/pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranController');

        //manajement guru
        Route::resource('manajemen/kehadiran-guru', '\App\Http\Controllers\ManajemenGuru\KehadiranGuruController');
        //manajemen keuangan siswa
        Route::resource('manajemen/keuangan-siswa/jenis-pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\JenisPembyaranController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-spp', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSppController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-semester', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSemesterController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-buku', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranBukuController');
        Route::resource('manajemen/keuangan-siswa/pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranController');
        //staff
        Route::resource('manajemen/staff', '\App\Http\Controllers\Staff\StaffController');
        //perpustakaan
        Route::resource('perpustakaan/data-buku', '\App\Http\Controllers\Perpustakaan\DataBukuController');
        Route::resource('perpustakaan/peminjaman-buku', '\App\Http\Controllers\Perpustakaan\PeminjamanBukuController');
        Route::resource('perpustakaan/pengembalian-buku', '\App\Http\Controllers\Perpustakaan\PengembalianBukuController');
        Route::resource('perpustakaan/petugas', '\App\Http\Controllers\Perpustakaan\PetugasPerpustakaanController');
        //inventories
        Route::resource('inventori/kategori-inventori', '\App\Http\Controllers\Inventori\KategoriInventoriController');
        Route::resource('inventori/tipe-inventori', '\App\Http\Controllers\Inventori\TipeInventoryController');
        Route::resource('inventori/gedung', '\App\Http\Controllers\Inventori\GedungController');
        Route::resource('inventori/tipe-donasi', '\App\Http\Controllers\Inventori\TipeDonasiController');
        Route::resource('inventori/asset', '\App\Http\Controllers\Inventori\AssetController');
        Route::resource('inventori/donasi', '\App\Http\Controllers\Inventori\DonasiController');
        Route::resource('inventori/barang', '\App\Http\Controllers\Inventori\BarangController');
        Route::resource('inventori/barang-masuk', '\App\Http\Controllers\Inventori\BarangMasukController');
        Route::resource('inventori/barang-keluar', '\App\Http\Controllers\Inventori\BarangKeluarController');
        Route::resource('inventori/spk-asset', '\App\Http\Controllers\Inventori\SPKAssetController');
        //accounting
        Route::resource('accounting/tipe-pajak', '\App\Http\Controllers\Accounting\TipePajakController');
        //pengeluaran
        Route::resource('accounting/pengeluaran/uang-masuk', '\App\Http\Controllers\Accounting\Pengeluaran\PengeluaranUangMasukController');
        Route::resource('accounting/pengeluaran/permintaan-dana', '\App\Http\Controllers\Accounting\Pengeluaran\PermintaanDanaController');
        Route::resource('accounting/pengeluaran/cek-list', '\App\Http\Controllers\Accounting\Pengeluaran\PengeluaranCekListController');
        Route::resource('accounting/pengeluaran/reibusment', '\App\Http\Controllers\Accounting\Pengeluaran\ReibustmentController');
        Route::resource('accounting/pengeluaran/jurnal-edc', '\App\Http\Controllers\Accounting\Pengeluaran\JurnalEdcController');
        Route::resource('accounting/pengeluaran/jurnal-uang-keluar', '\App\Http\Controllers\Accounting\Pengeluaran\JurnalUangKeluarController');
        Route::resource('accounting/pengeluaran/kas-mutasi', '\App\Http\Controllers\Accounting\Pengeluaran\JurnalKasMutasiController');
        Route::resource('accounting/pengeluaran/dana-pending', '\App\Http\Controllers\Accounting\Pengeluaran\DanaPendingController');
        //pemasukan
        Route::resource('accounting/pemasukan/rekening-siswa', '\App\Http\Controllers\Accounting\Pemasukan\RekeningSiswaController');
        Route::resource('accounting/pemasukan/jurnal-pbn', '\App\Http\Controllers\Accounting\Pemasukan\JurnalPbnController');
        Route::resource('accounting/pemasukan/jurnal-spp', '\App\Http\Controllers\Accounting\Pemasukan\JurnalSppController');
        Route::resource('accounting/pemasukan/jurnal-program-bulanan', '\App\Http\Controllers\Accounting\Pemasukan\JurnalProController');
        Route::resource('accounting/pemasukan/cut-off-siswa', '\App\Http\Controllers\Accounting\Pemasukan\CutOffSiswaController');
        Route::resource('accounting/pemasukan/hutang', '\App\Http\Controllers\Accounting\Pemasukan\HutangController');
        Route::resource('accounting/coa', '\App\Http\Controllers\Accounting\CoaController');
        
        //elearning
        Route::resource('elearning/tugas', '\App\Http\Controllers\Elearning\EtugasController');
        Route::resource('elearning/e-kelas', '\App\Http\Controllers\Elearning\EkelasController');
        Route::resource('elearning/materi', '\App\Http\Controllers\Elearning\EmateriController');
        Route::resource('elearning/quiz', '\App\Http\Controllers\Elearning\EquizController');
        Route::resource('elearning/pengumuman', '\App\Http\Controllers\Elearning\EpengumumanController');
        
        //pengumuman events
        Route::get('pengumuman/event/create', [
            'uses'      => '\App\Http\Controllers\Pengumuman\PengumumanEventsController@create',
            'as'        => 'pengumuman.event.create'
        ]);
        Route::post('pengumuman/event', [
            'uses'      => '\App\Http\Controllers\Pengumuman\PengumumanEventsController@addEvent',
            'as'        => 'pengumuman.event.store'
        ]);

        //cetak raport

app/HasilUjian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HasilUjian extends Model
{
    protected $table = 'hasil_ujians';

    protected $fillable = [
        'daftar_siswa_id',
        'pengetahuan_umum',
        'minat_bakat',
        'akademik',
        'status'
    ];

    public function siswa(){
        return $this->belongsTo('App\DaftarSiwa', 'daftar_siswa_id');
    }
}

resources/views/data_siswa/hasil_ujian/create.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Hasil Ujian</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">

				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
				    <li class="breadcrumb-item active" aria-current="page">Hasil Ujian</li>
				  </ol>
				</nav>

				 <!-- form start -->
	            {{ Form::open(array('route' => 'hasil-ujian.store')) }}
	              <div class="box-body">
                    <div class="col-md-12">
                            <div class="form-group">
                            <label for="nama">Daftar Siswa</label>
                             @if(!$siswas->isEmpty())
                                <select name="daftar_siswa_id" class="form-control">
                                    @foreach($siswas as $daftar_siswa)
                                        <option value="{{ $daftar_siswa->id }}">
                                            {{ $daftar_siswa->nama_lengkap }}
                                        </option>
                                    @endforeach
                                </select>
                             @else
                                <div class="dataempty">
                                    data empty
                                </div>
                             @endif
                            </div>
                        </div>
	                 <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Pengetahuan Umum</label>
	                  		{!! Form::text('pengetahuan_umum', old('pengetahuan_umum'), ['class' => 'form-control']) !!}
	                	</div>
	                 </div>
                     <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Minat Bakat</label>
	                  		{!! Form::text('minat_bakat', old('minat_bakat'), ['class' => 'form-control']) !!}
	                	</div>
	                 </div>
                     <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Akademik</label>
	                  		{!! Form::text('akademik', old('akademik'), ['class' => 'form-control']) !!}
	                	</div>
	                 </div>

					 <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Status</label>
	                  		<select name="status" class="form-control">
							  	<option value="diterima">Diterima</option>
							  	<option value="gagal">Gagal</option>
							</select>
	                	</div>
	                 </div>
                     
	                 <div class="col-md-6" style="margin-top: 15px;">
	                 	<div class="box-footer">
			                <button type="submit" class="btn btn-primary">Simpan</button>
			            </div>
	                 </div>
	              </div>
	              <!-- /.box-body -->
	            {!! Form::close() !!}
					
				</div>
				<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
@endsection

resources/views/data_siswa/hasil_ujian/edit.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Hasil Ujian</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">

				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
				    <li class="breadcrumb-item active" aria-current="page">Hasil Ujian</li>
				  </ol>
				</nav>

				 <!-- form start -->
                 {{ 
                   Form::model($hasilUjian, array(
                   'method' => 'PATCH',
                   'route' => array('hasil-ujian.update', $hasilUjian->id))) 
                }}
	              <div class="box-body">
                    <div class="col-md-12">
                            <div class="form-group">
                            <label for="nama">Daftar Siswa</label>
                             @if(!$siswas->isEmpty())
                                <select name="daftar_siswa_id" class="form-control">
                                    @foreach($siswas as $daftar_siswa)
                                        <option value="{{ $daftar_siswa->id }}">
                                            {{ $daftar_siswa->nama_lengkap }}
                                        </option>
                                    @endforeach
                                </select>
                             @else
                                <div class="dataempty">
                                    data empty
                                </div>
                             @endif
                            </div>
                        </div>
	                 <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Pengetahuan Umum</label>
	                  		{!! Form::text('pengetahuan_umum', old('pengetahuan_umum'), ['class' => 'form-control']) !!}
	                	</div>
	                 </div>
                     <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Minat Bakat</label>
	                  		{!! Form::text('minat_bakat', old('minat_bakat'), ['class' => 'form-control']) !!}
	                	</div>
	                 </div>
                     <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Akademik</label>
	                  		{!! Form::text('akademik', old('akademik'), ['class' => 'form-control']) !!}
	                	</div>
	                 </div>

					 <div class="col-md-4">
	                 	<div class="form-group">
	                  		<label for="nama">Status</label>
	                  		<select name="status" class="form-control">
							  	<option value="diterima">Diterima</option>
							  	<option value="gagal">Gagal</option>
							</select>
	                	</div>
	                 </div>
                     
	                 <div class="col-md-6" style="margin-top: 15px;">
	                 	<div class="box-footer">
			                <button type="submit" class="btn btn-primary">Simpan</button>
			            </div>
	                 </div>
	              </div>
	              <!-- /.box-body -->
	            {!! Form::close() !!}
					
				</div>
				<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
@endsection

resources/views/data_siswa/hasil_ujian/index.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Hasil Ujian</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
				    <li class="breadcrumb-item active" aria-current="page">Hasil Ujian</li>
				  </ol>
				</nav>
				<div class="box-header with-border">
					<a href="{{ route('hasil-ujian.create') }}" class="btn btn-sm btn-primary">
						<i class="fa fa-plus" aria-hidden="true"></i>
					</a>
				</div>
				<table class="table table-bordered">
					@if(!$hasilUjians->isEmpty())
						<tr>
							<th style="width: 10px">#</th>
							<th>Siswa</th>
							<th>Pengetahuan Umun</th>
							<th>Minat Bakat</th>
							<th>Akademik</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
						@foreach($hasilUjians as $hasilUjian)
							<tr>
								<td>{{ $loop->index +1 }}</td>
								<td>{{ $hasilUjian->siswa->nama_lengkap }}</td>
								<td>{{ $hasilUjian->pengetahuan_umum }}</td>
								<td>{{ $hasilUjian->minat_bakat }}</td>
								<td>{{ $hasilUjian->akademik }}</td>
								<td>{{ $hasilUjian->status }}</td>
								<td>
									<a href="{{ route('hasil-ujian.edit', ['hasil-ujian' => $hasilUjian->id]) }}" class="btn btn-sm btn-success">
										<i class="fa fa-pencil" aria-hidden="true"></i>
									</a>
									{!! Form::open(['route' => ['hasil-ujian.destroy', $hasilUjian->id], 'method' => 'DELETE', 'style' => 'display:inline;']) !!}
										<button class="btn btn-sm btn-danger btn-delete" type="submit">
											<i class="fa fa-trash" aria-hidden="true"></i>
										</button>
                                    {!! Form::close() !!}
								</td>
							</tr>
						@endforeach
					@else
                        <div class="alert alert-danger">
                            Data empty
                        </div>
                    @endif
				</table>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
				{{ $hasilUjians->links() }}
			</div> 
		</div>
		<!-- /.box -->
	</div>
@endsection