routes/web.php
]);

Route::get('accounting/filter/pengeluaran/permintaan-dana',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterPermintaanDanaController@search_permintaan_dana',
    'as'        => 'accounting.filter.pengeluaran.permintaan-dana'
]);

Route::get('accounting/filter/pengeluaran/cek-list',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterCekListController@search_cek_list',
    'as'        => 'accounting.filter.pengeluaran.cek-list'
]);

Route::get('accounting/filter/pengeluaran/reibustmen',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterReibustmenController@search_reibustment',
    'as'        => 'accounting.filter.pengeluaran.reibustmen'
]);

Route::get('accounting/filter/pengeluaran/jurnal-kas-edc',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterJurnalKasEDCController@search_jurnal_kas_edc',
    'as'        => 'accounting.filter.pengeluaran.jurnal-kas-edc'
]);

Route::get('accounting/filter/pengeluaran/uang-keluar',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterUangKeluarController@search_uang_keluar',
    'as'        => 'accounting.filter.pengeluaran.uang-keluar'
]);

Route::get('accounting/filter/pengeluaran/kas-mutasi',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterKasMutasiController@search_kas_mutasi',
    'as'        => 'accounting.filter.pengeluaran.kas-mutasi'
]);

Route::get('accounting/filter/pengeluaran/dana-pending',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pengeluaran\FilterDanaPendingController@search_dana_pending',
    'as'        => 'accounting.filter.pengeluaran.dana-pending'
]);
//pemasukan
Route::get('accounting/filter/pemasukan/rekening-siswa',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pemasukan\FilterRekeningSiswaController@search_rekening_siswa',
    'as'        => 'accounting.filter.pemasukan.rekening-siswa'
]);

Route::get('accounting/filter/pemasukan/jurnal-pbn',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pemasukan\FilterJurnalPBNController@search_jurnal_pbn',
    'as'        => 'accounting.filter.pemasukan.jurnal-pbn'
]);

Route::get('accounting/filter/pemasukan/jurnal-spp',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pemasukan\FilterJurnalSPPController@search_jurnal_spp',
    'as'        => 'accounting.filter.pemasukan.jurnal-spp'
]);

Route::get('accounting/filter/pemasukan/jurnal-pbb',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pemasukan\FilterJurnalPBBController@search_jurnal_pbb',
    'as'        => 'accounting.filter.pemasukan.jurnal-pbb'
]);

Route::get('accounting/filter/pemasukan/cos',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pemasukan\FilterCOSController@search_cos',
    'as'        => 'accounting.filter.pemasukan.cos'
]);

Route::get('accounting/filter/pemasukan/hutang',[
    'uses'      => '\App\Http\Controllers\Filter\Accounting\Pemasukan\FilterHutangController@search_hutang',
    'as'        => 'accounting.filter.pemasukan.hutang'
]);



//management role user
Route::resource('/roles', 'RoleController');

Route::resource('/users', 'UserController')->except([
    'show'
]);

Route::resource('data-master/data_sekolah', '\App\Http\Controllers\DataMaster\DataSekolahController');
        Route::resource('data-master/jurusan', '\App\Http\Controllers\DataMaster\JurusanController');
        Route::resource('data-master/kurikulum', '\App\Http\Controllers\DataMaster\KurikulumController');
        Route::resource('data-master/tahun_akademik', '\App\Http\Controllers\DataMaster\TahunAkademikController');
        Route::resource('data-master/ruang_kelas', '\App\Http\Controllers\DataMaster\RuangKelasController');
        Route::resource('data-master/agama', '\App\Http\Controllers\DataMaster\AgamaController');
        Route::resource('data-master/jabatan', '\App\Http\Controllers\DataMaster\JabatanController');
        Route::resource('data-master/bagian', '\App\Http\Controllers\DataMaster\BagianController');
        Route::resource('data-master/pendapatan', '\App\Http\Controllers\DataMaster\PendapatanController');
        Route::resource('data-master/status_karyawan', '\App\Http\Controllers\DataMaster\StatusKaryawanController');
        Route::resource('data-master/kendaraan', '\App\Http\Controllers\DataMaster\KendaraanController');
        Route::resource('data-master/rombongan_belajar', '\App\Http\Controllers\DataMaster\RombonganBelajarController');
        Route::resource('data-master/data_guru', '\App\Http\Controllers\DataMaster\DataGuruController');
        Route::resource('data-master/wali_kelas', '\App\Http\Controllers\DataMaster\WaliKelasController');
        Route::resource('data-master/kelas', '\App\Http\Controllers\DataMaster\KelasController');
        Route::resource('data-master/jenjang', '\App\Http\Controllers\DataMaster\JenjangController');
        //akademik
        Route::resource('akademik/mata_pelajaran', '\App\Http\Controllers\Akademik\MataPelajaranController');
        Route::resource('akademik/raport', '\App\Http\Controllers\Akademik\RaportController');
        Route::resource('manajemen/akademik/jadwal-mata-pelajaran', '\App\Http\Controllers\Akademik\JadwalMataPelajaranController');
        Route::resource('manajemen/siswa', '\App\Http\Controllers\ManajemenSiswa\SiswaController');
        Route::get('akademik/data-orang-tua', [
            'uses'      => '\App\Http\Controllers\Akademik\DataOrangTuaController@index',
            'as'        => 'data-orang-tua.index'
        ]);
        Route::resource('akademik/ekstrakurikuler', '\App\Http\Controllers\Akademik\EkstrakurikulerController');
        Route::resource('akademik/bimbingan-belajar', '\App\Http\Controllers\Akademik\BimbinganBelajarController');
        Route::resource('akademik/data-alumni', '\App\Http\Controllers\Akademik\DataAlumniController');
        Route::resource('akademik/mata-pelajar-perkelas', '\App\Http\Controllers\Akademik\MataPelajarPerkelasController');
        Route::resource('akademik/mata-pelajaran-guru', '\App\Http\Controllers\Akademik\MataPelajaranGuruController');
        Route::resource('akademik/grid-nilai', '\App\Http\Controllers\Akademik\GridNilaiController');
        Route::resource('akademik/siswa-perkelas', '\App\Http\Controllers\Akademik\SiswaPerkelasController');
        Route::resource('akademik/nilai-per-mata-pelajaran', '\App\Http\Controllers\Akademik\NilaiPermapelController');
        Route::resource('akademik/nilai-per-kelas', '\App\Http\Controllers\Akademik\NilaiPerkelasController');
        Route::resource('akademik/ekstra-siswa', '\App\Http\Controllers\Akademik\EktraSiswaController');
        //psb
        Route::resource('siswa/daftar-siswa', '\App\Http\Controllers\Psb\PsbDaftarSiswaController');
        Route::resource('psb/test-interview', '\App\Http\Controllers\Psb\TestInterviewController');
        Route::resource('psb/hasil-ujian', '\App\Http\Controllers\Psb\PsbHasilUjianController');
        Route::get('psb/siswa-diterima', [
            'uses'  => '\App\Http\Controllers\Psb\PsbSiswaDiterimaController@index',
            'as'    => 'siswa-diterima.index'
        ]);

        //manajemen keuangan siswa
        Route::resource('manajemen/keuangan-siswa/jenis-pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\JenisPembyaranController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-spp', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSppController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-semester', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSemesterController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-buku', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranBukuController');
        Route::resource('manajemen/keuangan-siswa/pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranController');

        //manajement guru
        Route::resource('manajemen/kehadiran-guru', '\App\Http\Controllers\ManajemenGuru\KehadiranGuruController');
        //manajemen keuangan siswa
        Route::resource('manajemen/keuangan-siswa/jenis-pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\JenisPembyaranController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-spp', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSppController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-semester', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranSemesterController');
        Route::resource('manajemen/keuangan-siswa/pembayaran-buku', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranBukuController');
        Route::resource('manajemen/keuangan-siswa/pembayaran', '\App\Http\Controllers\ManajemenKeuanganSiswa\PembayaranController');
        //staff
        Route::resource('manajemen/staff', '\App\Http\Controllers\Staff\StaffController');
        //perpustakaan
        Route::resource('perpustakaan/data-buku', '\App\Http\Controllers\Perpustakaan\DataBukuController');
        Route::resource('perpustakaan/peminjaman-buku', '\App\Http\Controllers\Perpustakaan\PeminjamanBukuController');
        Route::resource('perpustakaan/pengembalian-buku', '\App\Http\Controllers\Perpustakaan\PengembalianBukuController');
        Route::resource('perpustakaan/petugas', '\App\Http\Controllers\Perpustakaan\PetugasPerpustakaanController');
        //inventories
        Route::resource('inventori/kategori-inventori', '\App\Http\Controllers\Inventori\KategoriInventoriController');
        Route::resource('inventori/tipe-inventori', '\App\Http\Controllers\Inventori\TipeInventoryController');
        Route::resource('inventori/gedung', '\App\Http\Controllers\Inventori\GedungController');
        Route::resource('inventori/tipe-donasi', '\App\Http\Controllers\Inventori\TipeDonasiController');

app/Jurusan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jurusan extends Model
{
    protected $table = "jurusans";
    protected $fillable = [
    	'nama_jurusan',
    	'kode_jurusan'
    ];

    public function rombel(){
    	return $this->hasMany('App\RombonganBelajar');
    }

}

app/Http/Controllers/DataMaster/AgamaController.php
<?php
/**
*developer : hari
*/
namespace App\Http\Controllers\DataMaster;

use Redirect;
use Validator;
use App\Agama;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Http\Controllers\Controller;

class AgamaController extends Controller
{
    protected $request;
    protected $response;
    protected $limit = 10;

    public function __construct(
        Request $request,
        Response $response
    ) {
        $this->request      = $request;
        $this->response     = $response;
        $this->middleware('auth');
    }

    public function index()
    {
        $agamas         = Agama::orderBy('created_at', 'DESC')->paginate($this->limit);
        return view('data_master.agama.index', [
            'agamas'    => $agamas
        ]);
    }

    public function create()
    {
        return view('data_master.agama.create');
    }

    public function store()
    {
        $validate           = Validator::make($this->request->all(), [
            'nama'           => 'required|min:4'
        ]);

        if(!$validate->fails()){
            $agama                      = new Agama;
            $agama->nama                = $this->request->nama;
            $agama->save();
            return redirect()->route('agama.index')->with(['success' => 'Data berhasil disimpan']);
        }else{
            $errors = $validate->messages();

            return redirect()->route('agama.create')
                    ->withErrors($validate)
                    ->withInput($this->request->input());
        }
    }

    public function show($id)
    {
        
    }

    public function edit($id)
    {
        $agama      = Agama::findOrFail($id);
        return view('data_master.agama.edit', [
            'agama' => $agama
        ]);   
    }

    public function update($id)
    {
        $validate               = Validator::make($this->request->all(), [
            'nama'              => 'required|min:4'
        ]);

        if(!$validate->fails()){
            $agama                      = Agama::findOrFail($id);
            $agama->nama                = $this->request->nama;
            $agama->save();
            return redirect()->route('agama.index')->with(['success' => 'Data berhasil diupdate']);
        }else{
            $errors = $validate->messages();

            return redirect()->route('agama.edit')
                    ->withErrors($validate)
                    ->withInput($this->request->input());
        }
    }

    public function destroy($id)
    {
        $agama                      = Agama::findOrFail($id);
        $agama->delete();
        return redirect()->back()->with(['success' => 'Data berhasil dihapus']);
    }
}

app/Http/Controllers/DataMaster/BagianController.php
<?php
/**
*developer : hari , galan & adi
*/
namespace App\Http\Controllers\DataMaster;

use Redirect;
use Validator;
use App\Bagian;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Http\Controllers\Controller;

class BagianController extends Controller
{
    protected $request;
    protected $response;
    protected $limit = 10;

    public function __construct(
        Request $request,
        Response $response
    ) {
        $this->request      = $request;
        $this->response     = $response;
        $this->middleware('auth');
    }

    public function index()
    {
        $bagians            = Bagian::orderBy('created_at', 'DESC')->paginate($this->limit);
        return view('data_master.bagian.index', [
            'bagians'       => $bagians
        ]);
    }

    public function create()
    {
        return view('data_master.bagian.create');
    }

    public function store()
    {
        $validate           = Validator::make($this->request->all(), [
            'nama'           => 'required|min:4'
        ]);

        if(!$validate->fails()){
            $bagian                      = new Bagian;
            $bagian->nama                = $this->request->nama;
            $bagian->save();
            return redirect()->route('bagian.index')->with(['success' => 'Data berhasil disimpan']);
        }else{
            $errors = $validate->messages();

            return redirect()->route('bagian.create')
                    ->withErrors($validate)
                    ->withInput($this->request->input());
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $bagian         = Bagian::findOrFail($id);
        return view('data_master.bagian.edit', [
            'bagian'    => $bagian
        ]);
    }

    public function update($id)
    {
        $validate               = Validator::make($this->request->all(), [
            'nama'              => 'required|min:4'
        ]);
        if(!$validate->fails()){
            $bagian         = Bagian::findOrFail($id);
            $bagian->nama                = $this->request->nama;
            $bagian->save();
            return redirect()->route('bagian.index')->with(['success' => 'Data berhasil diupdate']);
        }else{
            $errors = $validate->messages();

            return redirect()->route('bagian.create')
                    ->withErrors($validate)
                    ->withInput($this->request->input());
        }
    }

    public function destroy($id)
    {
        $bagian         = Bagian::findOrFail($id);
        $bagian->delete();
        return redirect()->back()->with(['success' => 'Data berhasil dihapus']);
    }
}

resources/views/data_master/jurusan/create.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Create jurusan</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<div class="box-header with-border">
					<a href="{{ route ('data_sekolah.index') }}" class="btn btn-sm btn-primary">
						Back 
					</a>
				</div>

				 <!-- form start -->
	            {{ Form::open(array('route' => 'jurusan.store')) }}
	              <div class="box-body">
	                <div class="form-group">
	                  <label for="nama">Kode jurusan</label>
	                  {!! Form::text('kode_jurusan', old('kode_jurusan'), ['class' => 'form-control', 'required' => 'true']) !!}
	                </div>
	                <div class="form-group">
	                  <label for="Email">Nama jurusan</label>
	                  {!! Form::text('nama_jurusan', old('nama_jurusan'), ['class' => 'form-control', 'required' => 'true']) !!}
	                </div>
	              </div>
	              <!-- /.box-body -->

	              <div class="box-footer">
	                <button type="submit" class="btn btn-primary">Save Data</button>
	              </div>
	            {!! Form::close() !!}
					
				</div>
				<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
@endsection

resources/views/data_master/jurusan/edit.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Edit jurusan</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<div class="box-header with-border">
					<a href="#" class="btn btn-sm btn-primary">
						Back 
					</a>
				</div>

				 <!-- form start -->
	            {{ 
                   Form::model($jurusan, array(
                   'method' => 'PATCH',
                   'route' => array('jurusan.update', $jurusan->id))) 
                }}
	              <div class="box-body">
	                <div class="form-group">
	                  <label for="nama">Kode jurusan</label>
	                  {!! Form::text('kode_jurusan', old('kode_jurusan'), ['class' => 'form-control', 'required' => 'true']) !!}
	                </div>
	                <div class="form-group">
	                  <label for="Email">Nama jurusan</label>
	                  {!! Form::text('nama_jurusan', old('nama_jurusan'), ['class' => 'form-control', 'required' => 'true']) !!}
	                </div>
	              </div>
	              <!-- /.box-body -->

	              <div class="box-footer">
	                <button type="submit" class="btn btn-primary">Update Data</button>
	              </div>
	            {!! Form::close() !!}
					
				</div>
				<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
@endsection

resources/views/data_master/jurusan/index.blade.php
@extends('master')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Data Jurusan</h3>
			</div>
			@if (Session::has('success'))
				<div class="alert alert-success fade in">
                    <button data-dismiss="alert" class="close close-sm" type="button">
                        <i class="icon-remove"></i>
                    </button>
                    <strong>{{ Session::get('success') }}</strong>
                </div>
			@endif
			<!-- /.box-header -->
			<div class="box-body">
				<div class="box-header with-border">
					<a href="{{ route('jurusan.create') }}" class="btn btn-sm btn-primary">
						<i class="fa fa-plus" aria-hidden="true"></i>
					</a>
				</div>
				<table class="table table-bordered">
					@if(!$jurusans->isEmpty())
						<tr>
							<th style="width: 10px">#</th>
							<th>Kode jurusan</th>
							<th>Nama jurusan</th>
							<th>Action</th>
						</tr>
						@foreach($jurusans as $jurusan)
							<tr>
								<td>{{ $loop->index +1 }}</td>
								<td>{{ $jurusan->nama_jurusan }}</td>
								<td>{{ $jurusan->kode_jurusan }}</td>
								<td>
									<a href="{{ route('jurusan.edit', ['jurusan' => $jurusan->id]) }}" class="btn btn-sm btn-success">
										<i class="fa fa-pencil" aria-hidden="true"></i>
									</a>
									{!! Form::open(['route' => ['jurusan.destroy', $jurusan->id], 'method' => 'DELETE', 'style' => 'display:inline;']) !!}
									<button class="btn btn-sm btn-danger btn-delete" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">
										<i class="fa fa-trash" aria-hidden="true"></i>
									</button>
                                    {!! Form::close() !!}
								</td>
							</tr>
						@endforeach
					@else
                        <div class="alert alert-danger">
                            Data empty
                        </div>
                    @endif
				</table>
			</div>
			<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
@endsection